import os
from .nodes.MergeTextsNode import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_MERGE_TEXTS_NODE
from .nodes.MergeTextsNode import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_MERGE_TEXTS_NODE
from .nodes.TextareaNode import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_TEXTAREA_NODE
from .nodes.TextareaNode import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_TEXTAREA_NODE
from .nodes.EmptyLatentImageWithRotateNode import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_EMPTY_LATENT_IMAGE_WITH_ROTATE
from .nodes.EmptyLatentImageWithRotateNode import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_EMPTY_LATENT_IMAGE_WITH_ROTATE
from .nodes.ImageResultNode import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_IMAGE_RESULT_NODE
from .nodes.ImageResultNode import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_IMAGE_RESULT_NODE

NODE_CLASS_MAPPINGS = {
    **NODE_CLASS_MAPPINGS_MERGE_TEXTS_NODE,
    **NODE_CLASS_MAPPINGS_TEXTAREA_NODE,
    **NODE_CLASS_MAPPINGS_EMPTY_LATENT_IMAGE_WITH_ROTATE,
    **NODE_CLASS_MAPPINGS_IMAGE_RESULT_NODE,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS_MERGE_TEXTS_NODE,
    **NODE_DISPLAY_NAME_MAPPINGS_TEXTAREA_NODE,
    **NODE_DISPLAY_NAME_MAPPINGS_EMPTY_LATENT_IMAGE_WITH_ROTATE,
    **NODE_DISPLAY_NAME_MAPPINGS_IMAGE_RESULT_NODE,
}

WEB_DIRECTORY = os.path.join(os.path.dirname(os.path.realpath(__file__)), "web")

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
