from .nodes.LlamaNode import NODE_CLASS_MAPPINGS as TEXT_NODES
from .nodes.LlamaNode import NODE_DISPLAY_NAME_MAPPINGS as TEXT_DISPLAY_NAMES

NODE_CLASS_MAPPINGS = {**TEXT_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**TEXT_DISPLAY_NAMES}
